services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped